Create Major Bowman in SSB (move yet to be made)
HoeenCoder/Pokemon-Showdown pull request #272
Opened 2020-06-04 21:21 UTC by SSlayer9

2020-06-04 21:48 UTC, ghost requested changes

2020-06-04 21:48 UTC, Instructing commented on data/mods/ssb/moves.ts
> +		category: "Physical", // "Physical", "Special", or "Status"
set states that its special

2020-06-04 21:48 UTC, Instructing commented on data/mods/ssb/moves.ts
> +		onEffectiveness(typeMod, target, type) {
this isn't really how you do it. See how freeze dry works

2020-06-04 21:48 UTC, Instructing commented on data/mods/ssb/moves.ts
> +		critRatio: 1,
unnecessary

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/statuses.ts
> +			this.add(`c|${getName('Username')}|Never loved ya.`);
```suggestion
			this.add(`c|${getName('MajorBowman')}|This isn't Maury Povich!`);
		},
		onFaint() {
			this.add(`c|${getName('MajorBowman')}|Never loved ya.`);
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/random-teams.ts
> +		evs: {hp: 252, def: 252, spd: 4}, nature: 'Bold', level: 100, shiny: false,
```suggestion
		evs: {hp: 252, def: 252, spd: 4}, nature: 'Bold',
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +		critRatio: 1,
```suggestion
		},
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +			chance: 30,
```suggestion
			chance: 30,
			status: 'brn',
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +		},
```suggestion
```

Move these below `flags`

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +		flags: {protect: 1, mirror: 1}, // Move flags https://github.com/smogon/pokemon-showdown/blob/master/data/moves.js#L1-L27
```suggestion
		flags: {protect: 1, mirror: 1}, // Move flags https://github.com/smogon/pokemon-showdown/blob/master/data/moves.js#L1-L27
		onPrepareHit(target, source) {
			this.add('-anim', source, 'Poison Gas', target);
			this.add('-anim', source, 'Fire Spin', target);
		},
		onEffectiveness(typeMod, target, type) {
			if (type === 'Steel') return 1;
		},
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +		desc: "Has a 30% chance to burn the target, super effective against Steel.",
```suggestion
		desc: "Has a 30% chance to burn the target. This move's type effectiveness against Steel is changed to be super effective no matter what this move's type is.",
```

2020-06-04 21:51 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +		shortDesc: "30% chance to burn, super effective against Steel",
```suggestion
		shortDesc: "30% chance to burn. Super effective on Steel.",
```

2020-06-05 21:33 UTC, HoeenCoder commented
I messed up the rebase and had to wipe it and re-make it

2020-06-07 23:08 UTC, Instructing commented on data/mods/ssb/random-teams.ts
> +	Majorbowman: {
MajorBowman

2020-06-09 01:55 UTC, merged