Add Robb576
HoeenCoder/Pokemon-Showdown pull request #295
Opened 2020-06-06 12:25 UTC by Spandamn

2020-06-06 16:16 UTC, Spandamn commented
Okay wtf

2020-06-06 20:17 UTC, KrisXV requested changes

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/abilities.ts
> +	"thenumbersgame": {
```suggestion

	// Robb576
	thenumbersgame: {
```

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/abilities.ts
> +			const assignNewMoves = function (poke: Pokemon, moves: string[]) {
```suggestion
			const assignNewMoves (poke: Pokemon, moves: string[]) => {
```

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +	"integeroverflow": {
```suggestion
	integeroverflow: {
```

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +	"mode5offensive": {
```suggestion
	mode5offensive: {
```

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +	"mode7defensive": {
```suggestion
	mode7defensive: {
```

2020-06-06 20:17 UTC, KrisXV commented on data/mods/ssb/moves.ts
> +			this.add('-activate', source, 'move: Heal Bell');
```suggestion
			this.add('-activate', source, 'move: Mode [7: Defensive]');
```

2020-06-09 13:36 UTC, Spandamn commented
@Instructing @HoeenCoder quick quick merge it before more conflicts arise! lol

2020-06-09 13:42 UTC, Spandamn commented
i should prolly squash

2020-06-09 22:20 UTC, merged