Start xJoelituh
HoeenCoder/Pokemon-Showdown pull request #350
Opened 2020-07-22 22:54 UTC by SSlayer9

2020-07-23 00:11 UTC, SSlayer9 commented
Item is probably messed up. Contacted xJoel about something will update when they respond.

2020-08-02 05:28 UTC, xInstruct commented on data/mods/ssb/moves.ts
> +		name: "Move Name",
```suggestion
		name: "Burn Bone",
```

2020-08-02 05:34 UTC, xInstruct commented on data/mods/ssb/moves.ts
> +			if (target.status && target.status === 'brn') return;
```suggestion
			if (!target.trySetStatus('brn', source, move)) return;
```

2020-08-02 05:34 UTC, xInstruct commented on data/mods/ssb/moves.ts
> +			source.heal(source.baseMaxHp / 3);
```suggestion
			this.heal(source.baseMaxHp / 3);
```

2020-08-02 05:37 UTC, ghost requested changes
Add descriptions to the move and item and then Ill merge it after further review.

2020-08-07 03:43 UTC, ghost approved these changes

2020-08-07 06:26 UTC, xInstruct commented on data/mods/ssb/random-teams.ts
> +		evs: {hp: 248, atk: 8, spd: 252}, nature: 'Careful', shiny: true
```suggestion
		evs: {hp: 248, atk: 8, spd: 252}, nature: 'Careful', shiny: true,
```

2020-08-07 06:28 UTC, xInstruct commented on data/mods/ssb/moves.ts
> +				source.heal(source.baseMaxHp / 3);
```suggestion
				source.heal(source.baseMaxhp / 3);
```

2020-08-07 06:31 UTC, merged